---
title: "gdc"
author: "Xiaoni"
date: "9/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load the package required to read XML files.
library("XML")

# Also load the other required package.
library("methods")
```

```{r clinical folder}

dir='/Users/xiaonili/Downloads/gdc/clinical/'

# list.files() find all files

cl = lapply(list.files(path = dir,pattern = '*.xml$',recursive = T)
            , function(x){
  
              # Give the input file name to the function.
              result <- xmlParse(file = file.path(dir,x))
              
              # Exract the root node form the xml file.
              rootnode <- xmlRoot(result)
              
              # Exract the root node form the xml file.
              rootnode <- xmlRoot(result)
              
              # Convert the input xml file to a data frame.
              xmldataframe <- xmlToDataFrame(rootnode[2])
              return(t(xmldataframe))
              })

cl_df <- t(do.call(cbind,cl))
save(cl_df,file = 'GDC_TCGA_LUAD_clinical_df.Rdata')
```

```{r miRNAseq folder}
dir='/Users/xiaonili/Downloads/gdc/miRNAseq/'

mi = lapply(list.files(path = dir,pattern = '*.mirnas.quantification.txt$',recursive = T)
            , function(x){
            
              result <- read.table(file = file.path(dir,x), sep = '\t', header = T)[,1:2]
              return(result)
              })

mi_df <- t(do.call(cbind,mi))
dim(mi_df)

mi_df[1:4,1:4]
colnames(mi_df)=mi_df[1,]

#select line of even,which is read_count
mi_df=mi_df[seq(2,nrow(mi_df),by=2),]
mi_df[1:4,1:4]
```


